name: Publish packages

on:
  push:
    branches: [v2]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          # Fetch the full history, to build attribution.json
          fetch-depth: 0
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org/"
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

      - name: Prepare website v2
        run: |
          pnpm install
          pnpm docs-sync pull microsoft/TypeScript-Website-localizations#main 1
          pnpm bootstrap
          pnpm --filter=typescriptlang-org setup-playground-cache-bust
          pnpm build

      - name: Build website v2
        run: |
          pnpm build-site
          cp -r packages/typescriptlang-org/public site

      # Deploy
      - name: Deploy npm Packages
        run: |
          pnpm pleb publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
